### ISSUE TITLE
Read only Tiny MCE Editor

### ISSUE THREAD

**Issue by Sabarig83** [andz88/PCF.TinyMCE#11]
Could you please release another control of Tiny MCE Editor as a Read only version. This would be help to display the content that are not allowed to edit by the user.  I would like to collect the details in the editable control and display the results to other user group in the Read only control.

Thanks,
Sabari

**Comment by Sabarig83** [comment]
I built it and it works fine. Thanks

**Comment by syedibrahimmh** [comment]
@Sabarig83  Can you able to build it ? does it works in the test harness UI?
