### ISSUE TITLE
Can't build, missing reference files

### ISSUE THREAD

**Issue by syedibrahimmh** [andz88/PCF.TinyMCE#12]
Great work Andrew,
Can you pls add the missing dependent files refences (tinymce) into the repository.

this._tinymce = require('tinymce/tinymce');
		require('tinymce/themes/silver');
		require('tinymce/icons/default');

		// Any plugins you want to use has to be imported
		require('tinymce/plugins/paste');
		require('tinymce/plugins/link');
		require('tinymce/plugins/autoresize');
		require('tinymce/plugins/code');

**Comment by Sabarig83** [comment]
Please run the following command 
npm install
npm install tinymce

**Comment by syedibrahimmh** [comment]
@Sabarig83  Thanks mate.
