### ISSUE TITLE
Data is not loading all the time

### ISSUE THREAD

**Issue by Sabarig83** [andz88/PCF.TinyMCE#13]
Hi ANDZ,

The data is not loading all the time. I see there is an issue already reported and resolved. Can you please provide the source code for the fix and i will apply it in my solution.

Thanks,
Sabari

**Comment by andz88** [comment]
hi,

sorry I don't have it. I've implemented updateview as suggested therefore I marked it as fixed, but not sure what is the reporter's implementation of updateview.
