### ISSUE TITLE
Data not always displaying in control

### ISSUE THREAD

**Issue by lmaneville** [andz88/PCF.TinyMCE#3]
Hi,

I have added PCF.TinyMCE to a form. Really like it thank you!
Yet I found a small issue. 

When I open a form for an existing record, it sometimes take several seconds for Dynamics to recover the data. Meanwhile, fields are displayed empty. then they are completed once data is retrieved.
Yet PCF.TinyMCE control stays empty.

Maybe implementing updateView() in TinyMCEComponent/index.ts to set this._textValue will correct the issue.

I have not done any PCF development yet so I am not sure if my solution is correct. Do you think it make sense?

**Comment by andz88** [comment]
sorry for the late reply, do you have a specific configuration on how the form is configured and also the length of the field that you  bound with?

**Comment by lmaneville** [comment]
Hi andz,

No problem for the late reply, I did managed to sort myself in the meantime.
I don't think that I had a specific configuration to reproduce the issue, and it appeared in several forms. Undependently of the length of the field.
Yet I think the issue was easier to see in march, due to a specific behaviour when opening a record that has been changed since by Microsoft.

For your information, implementing the UpdateView() method correctly does correct the issue : this is because data is not always ready when the control is created, so the data arrives laterOn, trough the update view method.

Best Regards,

Laurent

**Comment by andz88** [comment]
thanks for the update Laurent. much appreciate the community spirit of sharing the knowledge :)

**Comment by lmaneville** [comment]
No problem, I appreciate it too!
Be carefull when implementing update view. I think that when I did tests writting text in the field does also call the update view, leading to strange behaviour. You may need to add a protection to that.
This is just memories and I didn't do many tests so nothing sure in that.

**Comment by Sabarig83** [comment]
> Hi andz,
> 
> No problem for the late reply, I did managed to sort myself in the meantime.
> I don't think that I had a specific configuration to reproduce the issue, and it appeared in several forms. Undependently of the length of the field.
> Yet I think the issue was easier to see in march, due to a specific behaviour when opening a record that has been changed since by Microsoft.
> 
> For your information, implementing the UpdateView() method correctly does correct the issue : this is because data is not always ready when the control is created, so the data arrives laterOn, trough the update view method.
> 
> Best Regards,
> 
> Laurent

Hi Laurent,

I do have the same issue. Could you please provide the updateview source code for the fix. Much appreciate.

Thanks,
Sabari
