### ISSUE TITLE
2000 character limitation

### ISSUE THREAD

**Issue by Sabarig83** [andz88/PCF.TinyMCE#9]
Can you please remove the 2000 character limitation or increase it to 500000 please

**Comment by andz88** [comment]
I don’t think I’ve put any limit on number of chars. Afaik, the limit is based on the field metadata itself

**Comment by Sabarig83** [comment]
You are correct. Thank you very much for Quick response.

**Comment by Sabarig83** [comment]
Can you please tell me the purpose of the New Document menu button.

![test](https://user-images.githubusercontent.com/69391692/89713078-dca05300-d95a-11ea-85ea-b9a94f15e0d8.png)

**Comment by andz88** [comment]
Standard out of the box of tinymce, to start over

**Comment by Sabarig83** [comment]
Hi ANDZ, 

We are planning to use this in our Microsoft dynamics instance. I do see that it comes with open license. Just would like confirm with you that this TINY license is not trail version valid for 30 days correct, its a open source correct. Kindly provide your feedback.

Thanks,
Sabari

**Comment by andz88** [comment]
I would recommend you to look at the licensing on their website. What I've done is just using the Core feature which is free - LGPL open source license (just need attribution "Powered by Tiny"). If you want to extend the code that created as-is with their paid plugins/features that is up to you. 
Ref: https://www.tiny.cloud/blog/tinymce-free-wysiwyg-html-editor/

**Comment by Sabarig83** [comment]
Thank you very much Andz. This is a great help.
